### ISSUE TITLE
Launch Todo

### ISSUE THREAD

**Issue by mcescalante** [OpenHumans/oh-github-source#1]
High level todo list for launching this integration:

**Ops**
- [ ] Move Github OAuth app to official key/secret
- [ ] Move OH app to official key/secret
- [ ] Transfer ownership of heroku app 
- [ ] set `SECURE_SSL_REDIRECT` env var
- [ ] Add heroku scheduler after confirmation of auto update task

**Development**
- [ ] Take a closer look at the Github data fetching rate limits (https://developer.github.com/v4/guides/resource-limitations/)
- [ ] Test and confirm the update data task behavior

**Comment by manaswinidas** [comment]
Is there any way I can help with this?

**Comment by carolinux** [comment]
hi @manaswinidas, I am working on the final integration of this at the moment. The list is not exactly up to date. Will let you know if I need any support from October onwards ^_^
